import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";  //remember jab be asa import krenga toh its means ka hum koi component nahi import kr rahay jisko humay later on nicha call krna hai its a stylesheet which will be applied. 
import { NavBar } from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
         {children}
         <Footer/>

      </body>
    </html>
  );
}
